services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDPLATFORM: ${BUILDPLATFORM:-linux/amd64}
        TARGETPLATFORM: ${TARGETPLATFORM:-linux/amd64}
    image: teddylee777/langgraph-mcp-agents:KOR-0.2.1
    platform: ${TARGETPLATFORM:-linux/amd64}
    ports:
      - "8585:8585"
    volumes:
      - ./.env:/app/.env:ro
      - ./data:/app/data:rw
      - ./config.json:/app/config.json
    env_file:
      - ./.env
    environment:
      - PYTHONUNBUFFERED=1
      - USE_LOGIN=${USE_LOGIN:-false}
      - USER_ID=${USER_ID:-}
      - USER_PASSWORD=${USER_PASSWORD:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NODE_OPTIONS=${NODE_OPTIONS:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8585/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
